spring.application.name=Noctra

jwt.secret=YjQ5NTY5NDQxMmY5YzNkZjEzNzRiNmU5ODk5NjUxMTk5NTA3MjNhMzkzNTk4M2M3MWJkMjg5N2Q5NmY5NGVmYw==
jwt.expiration=86400000

spring.datasource.url=jdbc:mysql://localhost:3306/noctra
spring.datasource.username=root
spring.datasource.password=root1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true