spring.application.name=Noctra

jwt.secret=YjQ5NTY5NDQxMmY5YzNkZjEzNzRiNmU5ODk5NjUxMTk5NTA3MjNhMzkzNTk4M2M3MWJkMjg5N2Q5NmY5NGVmYw==
jwt.expiration=86400000



spring.datasource.url=jdbc:mysql://localhost:3306/noctra
spring.datasource.username=root
spring.datasource.password=root1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true



tmdb.base-url=https://api.themoviedb.org/3
tmdb.token=eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJmYmE4MjcwNzk5NzFjMTIwYzgyYWRkYTI2YTQ4YzMxZSIsIm5iZiI6MTc4ODI4ODM4My40MzEsInN1YiI6IjZhOTcxZDdmNTAyNzM2OWMyNDVlZGU3ZCIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.H4s0I7PxwF1iyg98LjzPl48TL5cgdPTe2X_U_LydCJY



cors.allowed-origins=http://localhost:3000